# nuscenes_dir: nuscenes
# nuscenes_version: v1.0-mini
# label_dir: labels
nuscenes_dir: nuscenes_full_version
nuscenes_version: v1.0-trainval
label_dir: labels_full_version_all
log_dir: runs
checkpoint_dir: checkpoints
num_epochs_to_save_checkpoint: 50 # Save checkpoint every n epochs

# Network [ PON | H-PON ]
network: H-PON

# Number of epochs
epochs: 300

# Number of examples per mini-batch
batch_size: 24

# Number of dataloader threads
num_workers: 2

# Learning rate
lr: 0.001


# Top-left and bottom right coordinates of map region, in meters
map_extents: [-25.0, 1.0, 25.0, 50.0]
# Spacing between adjacent grid cells in the map, in meters
map_resolution: 0.25


# Vertical extents of the region of interest, in meters
ymin: -2
ymax: 4

# Approximate camera focal length used for constructing transformers
focal_length: 630.

# Number of intermediate channels in the transformer layer
tfm_channels: 64

# Number of output classes to predict
num_class: 14

# Topdown network options
topdown:

  # Number of feature channels at each layer of the topdown network
  channels: 128

  # Number of blocks in each layer
  layers: [4, 4]

  # Upsampling factor in each stage of the topdown network
  strides: [1, 2]

  # Type of residual block to use [ basic | bottleneck ]
  blocktype: bottleneck

# Whether to use Bayesian classifier
bayesian: False

# Class-specific weighting factors used to balance the cross entropy loss
class_weights:
  -    1.7    # drivable_area
  -    5.9    # ped_crossing
  -    3.3    # walkway
  -    4.6    # carpark
  -    8.0    # car
  -   10.3    # truck
  -   10.6    # bus
  -    6.9    # trailer
  -   11.8    # construction_vehicle
  -   30.1    # pedestrian
  -   33.6    # motorcycle
  -   41.2    # bicycle
  -   44.3    # traffic_cone
  -   15.9    # barrier

# Prior probability of a positive prediction, used to initialise classifier
prior:
  - 0.44679   # drivable_area
  - 0.02407   # ped_crossing
  - 0.14491   # walkway
  - 0.02994   # carpark
  - 0.02086   # car
  - 0.00477   # truck
  - 0.00156   # bus
  - 0.00189   # trailer
  - 0.00084   # construction_vehicle
  - 0.00119   # pedestrian
  - 0.00019   # motorcycle
  - 0.00012   # bicycle
  - 0.00031   # traffic_cone
  - 0.00176   # barrier

# Binary cross entropy loss weight
xent_weight: 1.0

# Max entropy uncertainty loss weight
uncert_weight: 0.001

# Method of weighting classes in loss function
weight_mode: sqrt_inverse