nuscenes_dir: nuscenes
nuscenes_version: v1.0-mini
label_dir: labels
log_dir: logs

# Number of epochs
epochs: 20

# Number of examples per mini-batch
batch_size: 16

# Number of dataloader threads
num_workers: 2

# Learning rate
lr: 0.001

train_scenes:
  [
    'scene-0061',
    'scene-0103',
    'scene-0553',
    'scene-0796',
    'scene-0916',
    'scene-1077',
    'scene-1094',
  ]
val_scenes:
  [ 
    'scene-0655',
    'scene-0757',
    'scene-1100',
  ]

# Top-left and bottom right coordinates of map region, in meters
map_extents: [-25.0, 1.0, 25.0, 50.0]
# Spacing between adjacent grid cells in the map, in meters
map_resolution: 0.25
